[package]
name = "async_usage"
version = "0.1.0"
edition = "2021"
authors = ["Simon Brummer <simon.brummer@posteo.de>"]
license = "MPL-2.0"
description = "Example: async usage of reachable"

[dependencies]
mempool_space = {path = "../..", features = ["async"]}
